locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include

from catalog import views
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.url')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    
]

catalog/models.py
from django.db import models
from django.urls import reverse #Used to generate URLs by reversing the URL patterns
import uuid # Requerida para las instancias de libros únicos
from django.contrib.auth.models import User
from datetime import date


# Create your models here.

class Genre(models.Model):
    '''
    Modelo que representa un género literario (p. ej. ciencia ficción, poesía, etc.). 
    '''
    name = models.CharField(
    max_length=200, 
    help_text= 'Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)'
    )

    def __str__(self):
        '''
        Cadena que representa a la instancia particular del modelo (p. ej. en el sitio de Administración)
        '''
        return self.name

class Language(models.Model):
    '''
    Model representing a Language (e.g. English, French, Japanese, etc.)
    '''

    name = models.CharField(
        max_length = 100,
        help_text = 'Enter the books natural language (e.g. English, French, Japanese etc.)'
    )

    def __str__(self):
        '''String for representing the Model object (in Admin site etc.)'''
        return self.name

class Book (models.Model):
    '''
    Modelo que representa un libro (pero no un Ejemplar específico).
    '''
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True
        )
    # ForeignKey, ya que un libro tiene un solo autor, pero el mismo autor puede haber escrito muchos libros.
    # 'Author' es un string, en vez de un objeto, porque la clase Author aún no ha sido declarada.
    
    summary = models.TextField(
        max_length=1000, 
        help_text= 'Ingrese una breve descripción del libro'
        )
    
    isbn = models.CharField(
        'ISBN', 
        max_length=13, 
        help_text='13 Caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'
        )
    
    genre = models.ManyToManyField(Genre, help_text='Seleccione un genero para este libro')
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    objects = models.Manager() # deshacerse de esa advertencia Vsc class has not object
    
    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        Esto se debe a que no podemos mostrar la infomacion de genre, es una relacion
        muchos a muchos, esto tendria un alto costo a la base de datos.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ]) # pylint: disable=E1101

    
    display_genre.short_description = 'Genre'    

    def __str__(self):
        '''
        String que representa al objeto Book
        '''
        return self.title

    def  get_absolute_url(self):
        """
        Devuelve el URL a una instancia particular de Book,
        Nota: esto permite en la pagina admin que al hacer clik en el
        nombre del libro podamos ir a sus detalles y editar
        """   
        return reverse('book-detail', args=[str(self.id)]) # pylint: disable=E1101

class BookInstance(models.Model):
    '''
    Modelo que representa una copia específica de un libro (i.e. que puede ser prestado por la biblioteca).
    '''
    id = models.UUIDField(
        primary_key = True, 
        default=uuid.uuid4, 
        help_text='ID único para este libro particular en toda la biblioteca'
        ) 
    
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=2000)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    objects = models.Manager()

    #
    LOAN_STATUS = (
        ('m','Maintenance'),
        ('o','On loan'),
        ('a', 'Available'),
        ('r','Reserved'),
    )

    status = models.CharField(
        max_length=1, 
        choices=LOAN_STATUS, 
        blank=True, 
        default='m', 
        help_text='Disponibilidad del libro'
        )
    
    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)



    def __str__(self):
        '''
        String para representar el Objeto del Modelo
        '''
        return '{0} ({1})'.format(self.id, self.book.__str__())

@property
def is_overdue(self):
    if self.due_back and date.today() > self.due_back:
        return True
    return False 


class Author(models.Model):
    '''
    Modelo que representa un autor
    '''
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    objects = models.Manager()
    
    def get_absolute_url(self):
        '''
         Retorna la url para acceder a una instancia particular de un autor.
        '''
        return reverse('author-detail', args=[str(self.id)]) # pylint: disable=E1101

    def __str__(self):
        return '{0} ({1})' .format(self.last_name, self.first_name)

catalog/views.py
from django.shortcuts import render, HttpResponse, Http404
# importa las clases de los modelos que usaremos para acceder a los datos en todas nuestras vistas.
from .models import Book, BookInstance, Author, Language, Genre

# importar clase de vistas genericas.
from  django.views import generic

# Create your views here.

def index(request):
    """
    Función vista para la página inicio del sitio.
    """
    """
    obtener el numero de veces que se visita la pagina
    """
    # Number of visits to this view, as counted in the session variable.
    num_visits= request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1

    #Generando contadores de alguno objetos especiales.
    num_books = Book.objects.all().count
    num_instances=BookInstance.objects.all().count()
    # Libros disponibles (status = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # El 'all()' esta implícito por defecto.
   
    # Renderiza la plantilla HTML index.html con los datos en la variable contexto
    return render(request,
        'index.html',
        context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors, 'num_visits':num_visits},
        )

class BookListView(generic.ListView):
    '''
    esta clase crea una vista generica basada en clase,
    para esto resive como parametro la clase vista de listas
    '''
    model = Book 
    paginate_by = 2


#OJO: con esta clase me da un error a la hora de pasar le id por url
class BookDetailView(generic.DetailView):
    model= BookInstance 


def book_detail_view(request,pk):
    try:
        book_id=Book.objects.get(pk=pk)
    except Book.DoesNotExist:
        raise Http404("Book does not exist")

    #book_id=get_object_or_404(Book, pk=pk)
    
    return render(
        request,
        'catalog/book_detail.html',
        context={'book':book_id,}
    )

class Authorlist(generic.ListView):
    model = Author


def author_detail_view(request,pk):
    try:
        author_id=Author.objects.get(pk=pk)
    except Author.DoesNotExist:
        raise Http404("Author does not exist")

    #book_id=get_object_or_404(Book, pk=pk)
    
    return render(
        request,
        'catalog/author_detail.html',
        context={'author':author_id,}
    )    



from django.contrib.auth.mixins import LoginRequiredMixin

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """
    Generic class-based view listing books on loan to current user. 
    """
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')    

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="{% url 'authors'%}">All authors</a></li>
      </ul>

      {% if user.is_authenticated %}
         <li>User: {{ user.get_username }}</li>
         <li><a href="{% url 'my-borrowed' %}">My Borrowed</a></li>
         <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
      {% else %}
         <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>   
      {% endif %}  

     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}
      
      {% endblock %}
  
{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}